# Dockerfile for Airline API Service
FROM python:3.13-slim

WORKDIR /app

# Copy requirements
COPY airline_api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY airline_api /app/airline_api
# Expose default port
EXPOSE 8001

CMD ["uvicorn", "airline_api.main:app", "--host", "0.0.0.0", "--port", "8001"]
