# Dockerfile for API Gateway Service
FROM python:3.13-slim

WORKDIR /app

# Copy requirements
COPY api_gateway/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY api_gateway /app/api_gateway
# Expose port
EXPOSE 8000

CMD ["uvicorn", "api_gateway.main:app", "--host", "0.0.0.0", "--port", "8000"]
